// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: data.sql

package data

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateVerifyEmail = `-- name: CreateVerifyEmail :one
INSERT INTO verify_emails (user_id, email, secret_code)
VALUES ($1, $2, $3)
RETURNING id, email, user_id, secret_code, is_used, created_at, expired_at
`

type CreateVerifyEmailParams struct {
	UserID     pgtype.UUID
	Email      string
	SecretCode string
}

func (q *Queries) CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error) {
	row := q.db.QueryRow(ctx, CreateVerifyEmail, arg.UserID, arg.Email, arg.SecretCode)
	var i VerifyEmail
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserID,
		&i.SecretCode,
		&i.IsUsed,
		&i.CreatedAt,
		&i.ExpiredAt,
	)
	return i, err
}

const UpdateUser = `-- name: UpdateUser :one
UPDATE users
SET is_email_verified = $1
WHERE id = $2
RETURNING id, username, email, password, description, avatar, created_at, is_email_verified, password_changed_at
`

type UpdateUserParams struct {
	IsEmailVerified bool
	ID              pgtype.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, UpdateUser, arg.IsEmailVerified, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Description,
		&i.Avatar,
		&i.CreatedAt,
		&i.IsEmailVerified,
		&i.PasswordChangedAt,
	)
	return i, err
}

const UpdateVerifyEmail = `-- name: UpdateVerifyEmail :one
UPDATE verify_emails
SET is_used = TRUE
WHERE id = $1
    AND secret_code = $2
    AND is_used = FALSE
    AND expired_at > now()
RETURNING id, email, user_id, secret_code, is_used, created_at, expired_at
`

type UpdateVerifyEmailParams struct {
	ID         int64
	SecretCode string
}

func (q *Queries) UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error) {
	row := q.db.QueryRow(ctx, UpdateVerifyEmail, arg.ID, arg.SecretCode)
	var i VerifyEmail
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserID,
		&i.SecretCode,
		&i.IsUsed,
		&i.CreatedAt,
		&i.ExpiredAt,
	)
	return i, err
}
