// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package data

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                pgtype.UUID
	Username          string
	Email             string
	Password          string
	Description       pgtype.Text
	Avatar            pgtype.Text
	CreatedAt         pgtype.Timestamp
	IsEmailVerified   bool
	PasswordChangedAt pgtype.Timestamptz
}

type VerifyEmail struct {
	ID         int64
	Email      string
	UserID     pgtype.UUID
	SecretCode string
	IsUsed     bool
	CreatedAt  pgtype.Timestamptz
	ExpiredAt  pgtype.Timestamptz
}
