server:
  kafka:
    addr: localhost:9092

data:
  database:
    name: ntube
    username: root
    password: "${DB_PASS:password}"
    host: localhost
    port: "5432"

trace:
  endpoint: http://127.0.0.1:14268/api/traces
