// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: 2fa/v1/2fa.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AuthSercie_VerifyEmail_FullMethodName = "/v1.AuthSercie/VerifyEmail"
)

// AuthSercieClient is the client API for AuthSercie service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthSercieClient interface {
	VerifyEmail(ctx context.Context, in *VerifyEmailRequest, opts ...grpc.CallOption) (*VerifyEmailResponse, error)
}

type authSercieClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthSercieClient(cc grpc.ClientConnInterface) AuthSercieClient {
	return &authSercieClient{cc}
}

func (c *authSercieClient) VerifyEmail(ctx context.Context, in *VerifyEmailRequest, opts ...grpc.CallOption) (*VerifyEmailResponse, error) {
	out := new(VerifyEmailResponse)
	err := c.cc.Invoke(ctx, AuthSercie_VerifyEmail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthSercieServer is the server API for AuthSercie service.
// All implementations must embed UnimplementedAuthSercieServer
// for forward compatibility
type AuthSercieServer interface {
	VerifyEmail(context.Context, *VerifyEmailRequest) (*VerifyEmailResponse, error)
	mustEmbedUnimplementedAuthSercieServer()
}

// UnimplementedAuthSercieServer must be embedded to have forward compatible implementations.
type UnimplementedAuthSercieServer struct {
}

func (UnimplementedAuthSercieServer) VerifyEmail(context.Context, *VerifyEmailRequest) (*VerifyEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyEmail not implemented")
}
func (UnimplementedAuthSercieServer) mustEmbedUnimplementedAuthSercieServer() {}

// UnsafeAuthSercieServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthSercieServer will
// result in compilation errors.
type UnsafeAuthSercieServer interface {
	mustEmbedUnimplementedAuthSercieServer()
}

func RegisterAuthSercieServer(s grpc.ServiceRegistrar, srv AuthSercieServer) {
	s.RegisterService(&AuthSercie_ServiceDesc, srv)
}

func _AuthSercie_VerifyEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthSercieServer).VerifyEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthSercie_VerifyEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthSercieServer).VerifyEmail(ctx, req.(*VerifyEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthSercie_ServiceDesc is the grpc.ServiceDesc for AuthSercie service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthSercie_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.AuthSercie",
	HandlerType: (*AuthSercieServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyEmail",
			Handler:    _AuthSercie_VerifyEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "2fa/v1/2fa.proto",
}
