server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    name: ntube
    username: root
    password: "${DB_PASS:password}"
    host: localhost
    port: "5432"
