server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
  kafka:
    server: "localhost:9092"
    topic: 2fa.email_verify.ts
data:
  database:
    name: ntube
    username: root
    password: "${DB_PASS:password}"
    host: localhost
    port: "5432"

  redis:
    addr: localhost:6379
    username: ""
    password: ""
    db: 0

token:
  duration: 3600s
  secret: change_me

trace:
  endpoint: http://127.0.0.1:14268/api/traces
