// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/nei7/ntube/app/2fa/internal/biz"
	"github.com/nei7/ntube/app/2fa/internal/conf"
	"github.com/nei7/ntube/app/2fa/internal/data"
	"github.com/nei7/ntube/app/2fa/internal/server"
	"github.com/nei7/ntube/app/2fa/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data_Database *conf.Data_Database, logger log.Logger) (*kratos.App, func(), error) {
	conn, err := data.NewPgxPool(data_Database)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(conn, logger)
	if err != nil {
		return nil, nil, err
	}
	emailVerifyRepo := data.NewEmailVerifyRepo(dataData, logger)
	emailVerifyUsecase := biz.NewEmailVerifyUsecase(emailVerifyRepo, logger)
	emailVerfifyService := service.NewEmailVerfifyService(emailVerifyUsecase)
	kafkaServer := server.NewKafkaServer(confServer, logger, emailVerfifyService)
	app := newApp(logger, kafkaServer)
	return app, func() {
		cleanup()
	}, nil
}
