// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package data

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID          uuid.UUID
	Username    string
	Email       string
	Password    string
	Description sql.NullString
	Avatar      sql.NullString
	CreatedAt   sql.NullTime
}
