// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID       uuid.UUID
	Email    string
	Password string
}

type Video struct {
	ID         uuid.UUID
	Path       string
	UploadedAt sql.NullTime
	OwnerID    uuid.UUID
}
