// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: video.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const CreateVideo = `-- name: CreateVideo :one
INSERT INTO videos (path, owner_id) VALUES ($1, $2) RETURNING id, path, uploaded_at, owner_id
`

type CreateVideoParams struct {
	Path    string
	OwnerID uuid.UUID
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, CreateVideo, arg.Path, arg.OwnerID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.UploadedAt,
		&i.OwnerID,
	)
	return i, err
}
